using System.Collections.ObjectModel;
using System.IO;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using TidyUp.Models.Domain;
using TidyUp.Models.Enums;
using TidyUp.Services;
using TidyUp.Services.Diagnostics;
using TidyUp.Services.Processing;
using TidyUp.Services.Simulation;
using TidyUp.ViewModels.Dialogs;

namespace TidyUp.ViewModels;

/// <summary>
/// Presentation wrapper for a single planned file action in the Side-by-Side Impact Preview.
/// </summary>
public partial class PlannedActionItemViewModel : ObservableObject
{
    public PlannedFileAction PlannedAction { get; }

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(CanBeApplied))]
    private bool _isApproved;

    [ObservableProperty]
    private string _executionStatus = "Pending";

    [ObservableProperty]
    private bool _isExecuted;

    [ObservableProperty]
    private bool _executionFailed;

    public PlannedActionItemViewModel(PlannedFileAction plannedAction)
    {
        PlannedAction = plannedAction;
        // Default to approved only if there are no conflicts
        _isApproved = !plannedAction.HasConflict;
    }

    public Guid Id => PlannedAction.Id;
    public string SourcePath => PlannedAction.SourcePath;
    public string? TargetPath => PlannedAction.TargetPath;
    public ActionType ActionType => PlannedAction.ActionType;
    public FileAction FileAction => PlannedAction.FileAction;
    public string RuleName => PlannedAction.RuleName;
    public long FileSizeBytes => PlannedAction.FileSizeBytes;
    public DateTime SourceModifiedDate => PlannedAction.SourceModifiedDate;
    public bool HasConflict => PlannedAction.HasConflict;
    public string? ConflictDescription => PlannedAction.ConflictDescription;
    public ConflictResolution ConflictResolution => PlannedAction.ConflictResolution;

    public string Extension
    {
        get
        {
            var ext = Path.GetExtension(SourcePath);
            return string.IsNullOrEmpty(ext) ? "(none)" : ext.ToLowerInvariant();
        }
    }

    public string ActionBadgeText => ActionType switch
    {
        ActionType.Move => "MOVE",
        ActionType.Copy => "COPY",
        ActionType.Rename => "RENAME",
        ActionType.ChangeExtension => "CHANGE EXT",
        ActionType.Delete => "DELETE",
        ActionType.ExtractArchive => "EXTRACT",
        ActionType.RunCommand => "COMMAND",
        _ => ActionType.ToString().ToUpperInvariant()
    };

    public string ActionBadgeBackground => ActionType switch
    {
        ActionType.Move => "#E3F2FD",
        ActionType.Copy => "#E0F2F1",
        ActionType.Rename => "#F3E5F5",
        ActionType.ChangeExtension => "#EDE7F6",
        ActionType.Delete => "#FFEBEE",
        ActionType.ExtractArchive => "#EFEBE9",
        ActionType.RunCommand => "#ECEFF1",
        _ => "#EEEEEE"
    };

    public string ActionBadgeForeground => ActionType switch
    {
        ActionType.Move => "#1976D2",
        ActionType.Copy => "#00796B",
        ActionType.Rename => "#7B1FA2",
        ActionType.ChangeExtension => "#512DA8",
        ActionType.Delete => "#D32F2F",
        ActionType.ExtractArchive => "#4E342E",
        ActionType.RunCommand => "#37474F",
        _ => "#424242"
    };

    public string StatusBadgeText
    {
        get
        {
            if (IsExecuted) return ExecutionFailed ? "FAILED" : "APPLIED";
            if (HasConflict) return "CONFLICT";
            return "READY";
        }
    }

    public string StatusBadgeBackground
    {
        get
        {
            if (IsExecuted) return ExecutionFailed ? "#FFEBEE" : "#E8F5E9";
            if (HasConflict) return "#FFF3E0";
            return "#E8F5E9";
        }
    }

    public string StatusBadgeForeground
    {
        get
        {
            if (IsExecuted) return ExecutionFailed ? "#C62828" : "#2E7D32";
            if (HasConflict) return "#E65100";
            return "#2E7D32";
        }
    }

    public bool CanBeApplied => IsApproved && !HasConflict && !IsExecuted;
}

/// <summary>
/// ViewModel for the Side-by-Side Impact Preview Window.
/// Displays planned actions generated by TASK-SAFE-01 dry-run simulation, provides
/// multi-criteria filtering, prevents execution when conflicts exist, and applies approved actions.
/// </summary>
public partial class PreviewViewModel : ObservableObject
{
    private readonly IExecutionPlanGenerator _planGenerator;
    private readonly IActionExecutor _actionExecutor;
    private readonly IExecutionDiscrepancyAnalyzer? _discrepancyAnalyzer;
    private readonly IBatchProcessingCoordinator _batchCoordinator;
    private CancellationTokenSource? _batchCancellationTokenSource;

    /// <summary>
    /// Delegate for requesting user confirmation before applying changes.
    /// Can be overridden in unit tests to test execution without UI message boxes.
    /// </summary>
    public Func<string, string, bool> ConfirmApplyHandler { get; set; }

    /// <summary>
    /// Delegate for presenting the Destructive Operation Safeguard modal when high-risk or large batch actions are detected.
    /// Can be overridden in unit tests to simulate user confirmation or cancellation without UI modals.
    /// </summary>
    public Func<SafeguardConfirmationViewModel, bool> SafeguardDialogHandler { get; set; }

    /// <summary>
    /// Delegate for displaying the post-execution discrepancy analyzer window when deviations occur.
    /// </summary>
    public Action<ExecutionDiscrepancyReport>? ShowDiscrepancySummaryHandler { get; set; }

    [ObservableProperty]
    private ExecutionDiscrepancyReport? _discrepancyReport;

    [ObservableProperty]
    private ObservableCollection<PlannedActionItemViewModel> _allItems = new();

    [ObservableProperty]
    private ObservableCollection<PlannedActionItemViewModel> _filteredItems = new();

    [ObservableProperty]
    private PlannedActionItemViewModel? _selectedItem;

    [ObservableProperty]
    private ExecutionPlan? _executionPlan;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(CanApplyChanges))]
    private bool _isLoading;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(CanApplyChanges))]
    [NotifyPropertyChangedFor(nameof(CanCancelExecution))]
    private bool _isExecuting;

    public bool CanCancelExecution => IsExecuting && _batchCancellationTokenSource is { IsCancellationRequested: false };

    [ObservableProperty]
    private double _executionProgress;

    [ObservableProperty]
    private string _statusMessage = "Ready";

    // Summary statistics
    [ObservableProperty]
    private int _totalScannedFiles;

    [ObservableProperty]
    private int _totalMatchedFiles;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(CanApplyChanges))]
    private int _conflictCount;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(CanApplyChanges))]
    private int _approvedCount;

    [ObservableProperty]
    private int _executedSuccessCount;

    [ObservableProperty]
    private int _executedFailureCount;

    // Filters
    [ObservableProperty]
    private ObservableCollection<string> _ruleFilterOptions = new() { "All Rules" };

    [ObservableProperty]
    private string _selectedRuleFilter = "All Rules";

    [ObservableProperty]
    private ObservableCollection<string> _extensionFilterOptions = new() { "All Extensions" };

    [ObservableProperty]
    private string _selectedExtensionFilter = "All Extensions";

    [ObservableProperty]
    private ObservableCollection<string> _actionTypeFilterOptions = new()
    {
        "All Actions",
        "Move",
        "Copy",
        "Rename",
        "ChangeExtension",
        "Delete",
        "ExtractArchive",
        "RunCommand"
    };

    [ObservableProperty]
    private string _selectedActionTypeFilter = "All Actions";

    [ObservableProperty]
    private bool _showConflictsOnly;

    [ObservableProperty]
    private string _searchText = string.Empty;

    public bool CanApplyChanges =>
        !IsLoading &&
        !IsExecuting &&
        ExecutionPlan != null &&
        AllItems.Any(i => i.IsApproved) &&
        !AllItems.Any(i => i.IsApproved && i.HasConflict);

    public PreviewViewModel(
        IExecutionPlanGenerator planGenerator,
        IActionExecutor actionExecutor,
        IExecutionDiscrepancyAnalyzer? discrepancyAnalyzer = null,
        IBatchProcessingCoordinator? batchCoordinator = null)
    {
        _planGenerator = planGenerator ?? throw new ArgumentNullException(nameof(planGenerator));
        _actionExecutor = actionExecutor ?? throw new ArgumentNullException(nameof(actionExecutor));
        _discrepancyAnalyzer = discrepancyAnalyzer;
        _batchCoordinator = batchCoordinator ?? new BatchProcessingCoordinator(_actionExecutor);

        ConfirmApplyHandler = DefaultConfirmApply;
        SafeguardDialogHandler = DefaultSafeguardDialog;
        ShowDiscrepancySummaryHandler = DefaultShowDiscrepancySummary;
    }

    /// <summary>
    /// Cooperatively cancels the in-flight batch execution.
    /// Halts scheduling next files while waiting for the currently active file operation to finish safely.
    /// </summary>
    [RelayCommand(CanExecute = nameof(CanCancelExecution))]
    public void CancelExecution()
    {
        if (IsExecuting && _batchCancellationTokenSource != null && !_batchCancellationTokenSource.IsCancellationRequested)
        {
            StatusMessage = "Cancelling batch... Waiting for in-flight operation to finish safely.";
            _batchCancellationTokenSource.Cancel();
            CancelExecutionCommand.NotifyCanExecuteChanged();
        }
    }

    private static bool DefaultConfirmApply(string message, string title)
    {
        return System.Windows.MessageBox.Show(
            message,
            title,
            System.Windows.MessageBoxButton.YesNo,
            System.Windows.MessageBoxImage.Question) == System.Windows.MessageBoxResult.Yes;
    }

    private static bool DefaultSafeguardDialog(SafeguardConfirmationViewModel vm)
    {
        var dialog = new Views.Dialogs.SafeguardConfirmationDialog(vm);
        var result = dialog.ShowDialog();
        return result == true && vm.IsConfirmed;
    }

    private static void DefaultShowDiscrepancySummary(ExecutionDiscrepancyReport report)
    {
        var vm = new ExecutionSummaryViewModel(report);
        var dialog = new Views.ExecutionSummaryWindow(vm);
        if (System.Windows.Application.Current?.MainWindow is { } owner)
        {
            dialog.Owner = owner;
        }
        dialog.ShowDialog();
    }

    /// <summary>
    /// Loads an already generated ExecutionPlan into the preview.
    /// </summary>
    public void LoadPlan(ExecutionPlan plan)
    {
        ArgumentNullException.ThrowIfNull(plan);

        ExecutionPlan = plan;
        TotalScannedFiles = plan.TotalScanned;
        TotalMatchedFiles = plan.TotalMatched;
        ConflictCount = plan.ConflictCount;

        AllItems.Clear();
        foreach (var action in plan.PlannedActions)
        {
            var itemVm = new PlannedActionItemViewModel(action);
            itemVm.PropertyChanged += (s, e) =>
            {
                if (e.PropertyName == nameof(PlannedActionItemViewModel.IsApproved))
                {
                    UpdateApprovedCount();
                    OnPropertyChanged(nameof(CanApplyChanges));
                    ApplyChangesCommand.NotifyCanExecuteChanged();
                }
            };
            AllItems.Add(itemVm);
        }

        PopulateFilterOptions();
        ApplyFilter();
        UpdateApprovedCount();

        StatusMessage = ConflictCount > 0
            ? $"Plan generated: {AllItems.Count} planned action(s), {ConflictCount} conflict(s) detected."
            : $"Plan generated: {AllItems.Count} planned action(s). Ready to apply.";

        OnPropertyChanged(nameof(CanApplyChanges));
        ApplyChangesCommand.NotifyCanExecuteChanged();
    }

    /// <summary>
    /// Runs a simulation for the specified rule and displays the resulting impact plan.
    /// </summary>
    [RelayCommand]
    public async Task SimulateRuleAsync(Rule rule)
    {
        if (rule == null)
        {
            StatusMessage = "No rule specified for preview.";
            return;
        }

        IsLoading = true;
        StatusMessage = $"Simulating rule '{rule.Name}' across monitored folders...";

        try
        {
            var plan = await _planGenerator.GeneratePlanAsync(rule);
            LoadPlan(plan);
        }
        catch (Exception ex)
        {
            ExecutionPlan = null;
            StatusMessage = $"Simulation error: {ex.Message}";
        }
        finally
        {
            IsLoading = false;
            OnPropertyChanged(nameof(CanApplyChanges));
            ApplyChangesCommand.NotifyCanExecuteChanged();
        }
    }

    /// <summary>
    /// Applies all approved planned actions with user confirmation and progress tracking.
    /// </summary>
    [RelayCommand(CanExecute = nameof(CanApplyChanges))]
    public async Task ApplyChangesAsync()
    {
        var approvedItems = AllItems.Where(i => i.IsApproved && !i.HasConflict && !i.IsExecuted).ToList();
        if (approvedItems.Count == 0)
        {
            StatusMessage = "No approved actions to apply.";
            return;
        }

        // Evaluate destructive-action safeguards (permanent deletion, overwrite, >50 files)
        var safeguardVm = new SafeguardConfirmationViewModel();
        bool requiresSafeguard = safeguardVm.EvaluateRisks(approvedItems);
        if (requiresSafeguard)
        {
            if (!SafeguardDialogHandler(safeguardVm))
            {
                StatusMessage = "Safeguard check cancelled: no files were modified.";
                return;
            }
        }
        else
        {
            // Standard confirmation for non-destructive operations
            var confirmMsg = $"Are you sure you want to apply {approvedItems.Count} approved file action(s)?\n\nThis will execute file operations on disk.";
            if (!ConfirmApplyHandler(confirmMsg, "Confirm Apply Changes"))
            {
                StatusMessage = "Apply changes cancelled by user.";
                return;
            }
        }

        _batchCancellationTokenSource = new CancellationTokenSource();
        CancelExecutionCommand.NotifyCanExecuteChanged();

        IsExecuting = true;
        ExecutionProgress = 0;
        ExecutedSuccessCount = 0;
        ExecutedFailureCount = 0;
        StatusMessage = $"Applying changes: 0 of {approvedItems.Count}...";

        var batchId = Guid.NewGuid();
        var plannedActions = approvedItems.Select(i => i.PlannedAction).ToList();
        var itemMap = approvedItems.ToDictionary(i => i.PlannedAction.Id);

        var progressReporter = new Progress<BatchProgressReport>(report =>
        {
            ExecutionProgress = report.Percentage;
            if (report.CurrentAction != null && itemMap.TryGetValue(report.CurrentAction.Id, out var itemVm))
            {
                itemVm.IsExecuted = true;
                if (report.LastActionResult?.Success == true)
                {
                    itemVm.ExecutionFailed = false;
                    itemVm.ExecutionStatus = "Completed";
                }
                else
                {
                    itemVm.ExecutionFailed = true;
                    itemVm.ExecutionStatus = report.LastActionResult?.ErrorMessage ?? "Failed";
                }
            }
            StatusMessage = $"Applying changes: {report.CompletedCount} of {report.TotalCount}...";
        });

        try
        {
            var batchResult = await _batchCoordinator.ExecuteBatchAsync(
                plannedActions,
                batchId,
                progressReporter,
                _batchCancellationTokenSource.Token);

            ExecutedSuccessCount = batchResult.SucceededCount;
            ExecutedFailureCount = batchResult.FailedCount;

            // Update any cancelled / skipped items in viewmodel
            foreach (var skipped in batchResult.ItemResults.Where(r => r.Skipped))
            {
                if (itemMap.TryGetValue(skipped.Action.Id, out var skippedVm))
                {
                    skippedVm.IsExecuted = false;
                    skippedVm.ExecutionStatus = "Cancelled";
                }
            }

            if (batchResult.WasCancelled)
            {
                StatusMessage = $"Execution cancelled: {batchResult.SucceededCount} succeeded, {batchResult.CancelledOrSkippedCount} skipped/untouched, {batchResult.FailedCount} failed.";
            }
            else
            {
                StatusMessage = $"Execution complete: {ExecutedSuccessCount} succeeded, {ExecutedFailureCount} failed.";
            }

            if (_discrepancyAnalyzer != null)
            {
                var executedResults = approvedItems.Select(item =>
                    (item.PlannedAction, new ActionResult
                    {
                        Success = !item.ExecutionFailed && item.IsExecuted,
                        ErrorMessage = item.ExecutionFailed ? item.ExecutionStatus : (item.IsExecuted ? null : "Cancelled"),
                        ResultPath = item.TargetPath,
                        TargetPath = item.TargetPath
                    })).ToList();

                DiscrepancyReport = _discrepancyAnalyzer.AnalyzeFromResults(
                    approvedItems.Select(i => i.PlannedAction),
                    executedResults,
                    batchId);

                if (DiscrepancyReport.HasAnyDiscrepancies)
                {
                    ShowDiscrepancySummaryHandler?.Invoke(DiscrepancyReport);
                }
            }
        }
        catch (Exception ex)
        {
            StatusMessage = $"Execution error: {ex.Message}";
        }
        finally
        {
            IsExecuting = false;
            _batchCancellationTokenSource?.Dispose();
            _batchCancellationTokenSource = null;
            CancelExecutionCommand.NotifyCanExecuteChanged();
            UpdateApprovedCount();
            OnPropertyChanged(nameof(CanApplyChanges));
            ApplyChangesCommand.NotifyCanExecuteChanged();
        }
    }

    /// <summary>
    /// Selects or deselects all unconflicted items in the current filtered view.
    /// </summary>
    [RelayCommand]
    public void SetAllApproved(bool approve)
    {
        foreach (var item in FilteredItems)
        {
            if (!item.HasConflict && !item.IsExecuted)
            {
                item.IsApproved = approve;
            }
        }
        UpdateApprovedCount();
        OnPropertyChanged(nameof(CanApplyChanges));
        ApplyChangesCommand.NotifyCanExecuteChanged();
    }

    partial void OnSelectedRuleFilterChanged(string value) => ApplyFilter();
    partial void OnSelectedExtensionFilterChanged(string value) => ApplyFilter();
    partial void OnSelectedActionTypeFilterChanged(string value) => ApplyFilter();
    partial void OnShowConflictsOnlyChanged(bool value) => ApplyFilter();
    partial void OnSearchTextChanged(string value) => ApplyFilter();

    public void ApplyFilter()
    {
        var query = AllItems.AsEnumerable();

        if (ShowConflictsOnly)
        {
            query = query.Where(i => i.HasConflict);
        }

        if (!string.IsNullOrEmpty(SelectedRuleFilter) && SelectedRuleFilter != "All Rules")
        {
            query = query.Where(i => string.Equals(i.RuleName, SelectedRuleFilter, StringComparison.OrdinalIgnoreCase));
        }

        if (!string.IsNullOrEmpty(SelectedExtensionFilter) && SelectedExtensionFilter != "All Extensions")
        {
            query = query.Where(i => string.Equals(i.Extension, SelectedExtensionFilter, StringComparison.OrdinalIgnoreCase));
        }

        if (!string.IsNullOrEmpty(SelectedActionTypeFilter) && SelectedActionTypeFilter != "All Actions")
        {
            query = query.Where(i => string.Equals(i.ActionType.ToString(), SelectedActionTypeFilter, StringComparison.OrdinalIgnoreCase));
        }

        if (!string.IsNullOrWhiteSpace(SearchText))
        {
            var search = SearchText.Trim();
            query = query.Where(i =>
                i.SourcePath.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                (i.TargetPath != null && i.TargetPath.Contains(search, StringComparison.OrdinalIgnoreCase)));
        }

        FilteredItems = new ObservableCollection<PlannedActionItemViewModel>(query.ToList());
    }

    private void PopulateFilterOptions()
    {
        var rules = AllItems.Select(i => i.RuleName).Where(r => !string.IsNullOrEmpty(r)).Distinct().OrderBy(r => r).ToList();
        RuleFilterOptions = new ObservableCollection<string> { "All Rules" };
        foreach (var r in rules) RuleFilterOptions.Add(r);

        var extensions = AllItems.Select(i => i.Extension).Distinct().OrderBy(e => e).ToList();
        ExtensionFilterOptions = new ObservableCollection<string> { "All Extensions" };
        foreach (var ext in extensions) ExtensionFilterOptions.Add(ext);

        SelectedRuleFilter = "All Rules";
        SelectedExtensionFilter = "All Extensions";
        SelectedActionTypeFilter = "All Actions";
        ShowConflictsOnly = false;
        SearchText = string.Empty;
    }

    private void UpdateApprovedCount()
    {
        ApprovedCount = AllItems.Count(i => i.IsApproved && !i.IsExecuted);
    }
}

